# Generated by Django 4.2.2 on 2023-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
